In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [2]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [3]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [9]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)
clf.fit(digits.data[:-1], digits.target[:-1])  #SVC(C=100.0, gamma=0.001)

SVC(C=100.0, gamma=0.001)

In [10]:
clf.predict(digits.data[-1:])

array([8])

In [11]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC
X, y = load_iris(return_X_y=True)

clf = SVC()
clf.set_params(kernel='linear').fit(X, y)
#SVC(kernel='linear')
clf.predict(X[:5])
#array([0, 0, 0, 0, 0])

clf.set_params(kernel='rbf').fit(X, y)
#SVC()
clf.predict(X[:5])
#array([0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0])

In [12]:
import numpy as np
import pandas as pd
import os
import csv
league = input("Select league: ").replace(" ", "_").lower()
year = input("Select year: ")

input_file = rf'cleaned_datasets/{league}/{year}/cleaned_dataset_{league}_{year}.csv'

try:
    if os.path.exists(input_file):
        with open(input_file) as file:
            data = csv.reader(file) #load json file
            #print("Type:", type(data))
            # comma delimited is the default
            df = pd.read_csv(input_file, header = 0)

            # for space delimited use:
            # df = pd.read_csv(input_file, header = 0, delimiter = " ")

            # for tab delimited use:
            # df = pd.read_csv(input_file, header = 0, delimiter = "\t")

            # put the original column names in a python list
            original_headers = list(df.columns.values)

            # remove the non-numeric columns
            df = df._get_numeric_data()

            # put the numeric column names in a python list
            numeric_headers = list(df.columns.values)

            # create a numpy array with the numeric values for input into scikit-learn
            numpy_array = df.as_matrix()

            # reverse the order of the columns
            numeric_headers.reverse()
            reverse_df = df[numeric_headers]

            # write the reverse_df to an excel spreadsheet
            reverse_df.to_excel('path_to_file.xls')
        
    else:
        print("This file does not exist - please create before trying to load to database")
except:
    "File not loaded to database"

In [27]:
import numpy as np
# load the CSV file as a numpy matrix
f = open(rf'cleaned_datasets/{league}/{year}/cleaned_dataset_{league}_{year}.csv')
f.readline()  # skip the header
data = np.genfromtxt(fname = f, delimiter = ',')
data

array([[  0.,   1.,   0., ...,   1.,   1.,   1.],
       [  1.,   1.,   1., ...,   3.,   1.,   4.],
       [  2.,   1.,   1., ...,   0.,   4.,   4.],
       ...,
       [303.,  34.,   2., ...,   7., 463., 361.],
       [304.,  34.,   1., ...,  21., 466., 361.],
       [305.,  34.,   2., ...,  16., 466., 364.]])

In [28]:
# separate the data from the target attributes
X = data[:,0:7]
y = data[:,8]

In [29]:
from sklearn import kernel_approximation
transformer = kernel_approximation.RBFSampler()
X_new = transformer.fit_transform(X)
X_new.dtype

dtype('float64')